# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  everforest = {
    pname = "everforest";
    version = "b10ed9a8b37d6b7448908be98ff8f58f550adc48";
    src = fetchFromGitHub {
      owner = "sainnhe";
      repo = "everforest";
      rev = "b10ed9a8b37d6b7448908be98ff8f58f550adc48";
      fetchSubmodules = false;
      sha256 = "sha256-2mljM3Gwl3oXa2xF5Nh+WXDrjJWhwgRHgRiTJieWhsg=";
    };
    date = "2025-12-06";
  };
}
