# User keys are stored in ~/.ssh - they are generated using ssh-keygen. Put user key on every key so we can edit everything with user key.
#
# System keys are generated by system, they are stored in /etc/ssh. Nixos will not see user keys when decrypting, it uses system keys to *decrypt*,
# so adding system key lets a specific system read a secret.
#
# Basically use user keys (shared across devices) to edit secrets, use device specific system keys to read secrets.
let
  keys = import ./ssh_keys.nix;
in {
  "wifi/empress.age".publicKeys = [keys.systems.latte keys.users.jeffreyli];
  "wifi/wabuwabu.age".publicKeys = [keys.systems.latte keys.users.jeffreyli];
  "cloudflared-environment.age".publicKeys = [keys.systems.latte keys.users.jeffreyli];
}
